#!/bin/bash

rm -rf "${TRIM_APPDEST_VOL}/@appdata/${TRIM_APPNAME}"
rm -rf "${TRIM_APPDEST_VOL}/@appmeta/${TRIM_APPNAME}"
rm -rf "${TRIM_APPDEST_VOL}/@apphome/${TRIM_APPNAME}"
rm -rf "${TRIM_APPDEST_VOL}/@appconf/${TRIM_APPNAME}"

exit 0